version: 2.1
orbs:
  terraform: circleci/terraform@3.2.0

commands:
  reattach:
    steps:
      - attach_workspace:
         at: .

jobs:
  checkout:
    docker:
      - image: cimg/base:2021.03
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - .
  fmt:
    executor:
      name: terraform/default
      tag: 1.0.9
    steps:
      - reattach
      - terraform/fmt
  validate:
    executor:
      name: terraform/default
      tag: 1.0.9
    steps:
      - reattach
      - terraform/validate

workflows:
  version: 2
  main:
    jobs:
      - checkout
      - fmt:
          requires:
            - checkout
      - validate:
          requires:
            - checkout
